### ISSUE TITLE
Feature request: other npanel category 

### ISSUE THREAD

**Issue by Ulf3000** [Pullusb/GP_clipboard#1]
hey man , great addon there , but could you add an option to select the actual n-panel name its displayed in ? 
then i could group it together with the other grease pencil addons and not have so many different n panel tabs (the biggest shortcoming of blenders ui). 

the bundled "grease pencil tools" addon has such a function and option in the preferences, so maybe you can copy the code from there 

thanx a lot for your efforts so far

**Comment by Pullusb** [comment]
Sure, I'll implement on this one as I've done for the official addon (it was you how asked for it in the first place if I'm not mistaken)
Will do that when I get some free time. (busy right now).

**Comment by Pullusb** [comment]
Ok done in the new 1.3.0
Not a big fan of adding addon-prefs just for this, but I definitely agree that it's better for users.
Anyway, happy blending !

**Comment by Pullusb** [comment]
@Ulf3000 just so you know, I added a bugfix for potential error in keymap
you should use the 1.3.1 I just pushed.
Have a nice WE

**Comment by Ulf3000** [comment]
ok thanx man!   you da best :)
