### ISSUE TITLE
Select option on draw mode

### ISSUE THREAD

**Issue by rcevik** [Pullusb/GP_clipboard#6]
Hi Samuel,

First of all thanks a lot for you for this great addon!! It is very useful for a hand drawn animator.
Would it be possible if there is a "select lasso" option over cut/copy stoke options
on "draw mode". I know there are shortcuts for edit mode  but switching modes frequently is
quite pain for someone uses softwares like Harmony or Tv paint. 

Addition to that after selecting with lasso, transform options (move-rotate-scale) automatically appears on Harmony and that saves  more time on that side as well. TvPaint has this option as a "stamp" function which allows using and transforming duplicates visually which is very handy.

Thanks again!

**Comment by Pullusb** [comment]
Hi,
I think I see what you want.
Fun thing is, I'm developing something close to this feature at the moment (not multi selection though)

I plan to make it my first paid addon.
Will probably appear on [my gumroad](https://pullusb.gumroad.com/) in one or two weeks.

Will keep you informed.

**Comment by rcevik** [comment]
Oh, great! Looking forward to hear about it!

Samuel Bernou ***@***.***>, 16 Eyl 2021 Per, 15:45 tarihinde
şunu yazdı:

**Comment by Pullusb** [comment]
@rcevik Just keep you informed as promised, I released the addon I talked about today: https://pullusb.gumroad.com/l/gp_draw_transform

**Comment by rcevik** [comment]
Thank you! This one seems very useful as usual, especially for clean up I
think.

Does it works with lasso? Because other hand drawn animation programs'
case, this feature also used for multiple strokes as well. For example
after selecting head, arms etc..
a moveable pivot appears and  transforms manually like a neck or  wrist.

Best,

Samuel Bernou ***@***.***>, 4 Eki 2021 Pzt, 00:38 tarihinde
şunu yazdı:

**Comment by Pullusb** [comment]
Hi,
No it's not, it's intended to work with single strokes only.
The idea is not to replace edit, just have something to make a quick readjust without making a switch. Often just to tweak the  last stroke in my personal use case.

I think for your case, you should just create a shortcut to make edit/draw mode access faster.
On the node drop-down menu you can right-click on `edit mode` and add shortcut, let's say `W`, and on `draw mode` you do the same with `F` for example. Then you will be able to switch faster between those two by just hitting.
A lot of 2D animator I know did this.

Bests,

**Comment by rcevik** [comment]
Hi,

I guessed so. Again, your new addon looks very very handy for single stroke.

Yeah, I already created shortcuts as you mentioned but that transformers
not very stable in my case. Your addon looks more
promising to me if there's an option for multiple strokes as well.

Thank you!








Samuel Bernou ***@***.***>, 5 Eki 2021 Sal, 12:27 tarihinde
şunu yazdı:
